import React from "react";
import CreditsWrapper from "./CreditsWrapper";

export default () => (
  <CreditsWrapper>
    Website by{" "}
    <a target="_blank" href="https://james-leung.github.io/">
      James Leung
    </a>
    ; <p></p>
    Template by{" "}
    <a target="_blank" href="https://gitlab.com/nic.neale">
      Nic Neale
    </a>
    ; <p></p>
    Users generated by{" "}
    <a target="_blank" href="https://randomuser.me/">
      https://randomuser.me/
    </a>
  </CreditsWrapper>
);
